<?php
/**********************************************************************
Copyright (C) Grameen Solutions Ltd.(www.grameensolutions.com)
***********************************************************************/
//function get_employee_list(){
//     $sql = "select
//                   employee_id, 
//                   concat(emp_firstname,' ',emp_lastname) as name
//           from 
//                   ".TB_PREF."employee 
//           order by
//                   emp_firstname";
//
//   return $sql;
//}
?>